// This file is auto-generated by the server. Do not edit directly.
const salesSummaryData = [
  {
    "table": "Seat 1",
    "timestamp": "2026-07-12T16:22:41.781Z",
    "items": [
      {
        "name": "Veg Burger",
        "qty": 4,
        "price": 130,
        "total": 520
      },
      {
        "name": "Veg Cheesy Burger",
        "qty": 1,
        "price": 150,
        "total": 150
      },
      {
        "name": "Korean Veg Burger",
        "qty": 2,
        "price": 180,
        "total": 360
      },
      {
        "name": "Chicken Burger",
        "qty": 1,
        "price": 150,
        "total": 150
      }
    ],
    "total": 1180
  }
];
