// This file is auto-generated by the server. Do not edit directly.
const salesEndingsData = [
  {
    "timestamp": 1783873323979,
    "total": 610
  },
  {
    "timestamp": 1783874147622,
    "total": 1180
  }
];
