const express = require('express');
const cors = require('cors');
const fs = require('fs');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 3000;
const PASSWORD = 'admin123'; // Default admin password

app.use(cors());
app.use(express.json());

// Serve static files of the parlour
app.use(express.static(__dirname));

// Login Endpoint
app.post('/api/admin/login', (req, res) => {
    const { password } = req.body;
    if (password === PASSWORD) {
        return res.json({ success: true, token: 'moonlight-session-token-9988' });
    } else {
        return res.status(401).json({ success: false, message: 'Invalid Password' });
    }
});

// Get Menu Endpoint
app.get('/api/menu', (req, res) => {
    const menuPath = path.join(__dirname, 'menu.json');
    fs.readFile(menuPath, 'utf8', (err, data) => {
        if (err) {
            return res.status(500).json({ error: 'Failed to read menu file' });
        }
        try {
            const menu = JSON.parse(data);
            res.json(menu);
        } catch (e) {
            res.status(500).json({ error: 'Invalid JSON in menu file' });
        }
    });
});

// Save Menu Endpoint
app.post('/api/menu', (req, res) => {
    // Basic auth check using custom token in header
    const token = req.headers['authorization'];
    if (token !== 'Bearer moonlight-session-token-9988') {
        return res.status(403).json({ error: 'Unauthorized access' });
    }

    const newMenu = req.body;
    if (!newMenu || !Array.isArray(newMenu.sections)) {
        return res.status(400).json({ error: 'Invalid menu data format' });
    }

    const menuJsonPath = path.join(__dirname, 'menu.json');
    const menuJsPath = path.join(__dirname, 'menu.js');

    // 1. Write menu.json
    fs.writeFile(menuJsonPath, JSON.stringify(newMenu, null, 2), 'utf8', (err) => {
        if (err) {
            console.error('Error writing menu.json:', err);
            return res.status(500).json({ error: 'Failed to save menu.json' });
        }

        // 2. Write menu.js for file:/// fallback
        const jsContent = `// This file is auto-generated by the server. Do not edit directly.\nconst menuData = ${JSON.stringify(newMenu, null, 2)};\n`;
        fs.writeFile(menuJsPath, jsContent, 'utf8', (err2) => {
            if (err2) {
                console.error('Error writing menu.js:', err2);
                return res.status(500).json({ error: 'Failed to save menu.js' });
            }

            console.log('Menu saved successfully and files updated.');
            res.json({ success: true, message: 'Menu saved and synced successfully' });
        });
    });
});

// GET Sales Summary
app.get('/api/sales', (req, res) => {
    const filePath = path.join(__dirname, 'sales_summary.json');
    fs.readFile(filePath, 'utf8', (err, data) => {
        if (err) return res.status(500).json({ error: 'Failed to read sales summary' });
        try {
            res.json(JSON.parse(data));
        } catch (e) {
            res.json([]);
        }
    });
});

// POST new transaction
app.post('/api/sales', (req, res) => {
    const txn = req.body;
    const jsonPath = path.join(__dirname, 'sales_summary.json');
    const jsPath = path.join(__dirname, 'sales_summary.js');

    fs.readFile(jsonPath, 'utf8', (err, data) => {
        let sales = [];
        if (!err) {
            try { sales = JSON.parse(data); } catch (e) { sales = []; }
        }
        sales.push(txn);

        fs.writeFile(jsonPath, JSON.stringify(sales, null, 2), 'utf8', (err2) => {
            if (err2) return res.status(500).json({ error: 'Failed to write sales summary' });
            
            const jsContent = `// This file is auto-generated by the server. Do not edit directly.\nconst salesSummaryData = ${JSON.stringify(sales, null, 2)};\n`;
            fs.writeFile(jsPath, jsContent, 'utf8', (err3) => {
                if (err3) console.error('Failed to write sales_summary.js:', err3);
                res.json({ success: true, message: 'Transaction saved' });
            });
        });
    });
});

// Clear Sales Summary
app.post('/api/sales/clear', (req, res) => {
    const jsonPath = path.join(__dirname, 'sales_summary.json');
    const jsPath = path.join(__dirname, 'sales_summary.js');

    fs.writeFile(jsonPath, '[]', 'utf8', (err) => {
        if (err) return res.status(500).json({ error: 'Failed to clear sales summary' });
        const jsContent = `// This file is auto-generated by the server. Do not edit directly.\nconst salesSummaryData = [];\n`;
        fs.writeFile(jsPath, jsContent, 'utf8', (err2) => {
            if (err2) console.error('Failed to write sales_summary.js:', err2);
            res.json({ success: true, message: 'Sales summary cleared' });
        });
    });
});

// Delete a specific transaction
app.post('/api/sales/delete', (req, res) => {
    const { timestamp } = req.body;
    const jsonPath = path.join(__dirname, 'sales_summary.json');
    const jsPath = path.join(__dirname, 'sales_summary.js');

    fs.readFile(jsonPath, 'utf8', (err, data) => {
        if (err) return res.status(500).json({ error: 'Failed to read sales summary' });
        let sales = [];
        try { sales = JSON.parse(data); } catch (e) { sales = []; }

        const updatedSales = sales.filter(txn => String(txn.timestamp) !== String(timestamp));

        fs.writeFile(jsonPath, JSON.stringify(updatedSales, null, 2), 'utf8', (err2) => {
            if (err2) return res.status(500).json({ error: 'Failed to write sales summary' });

            const jsContent = `// This file is auto-generated by the server. Do not edit directly.\nconst salesSummaryData = ${JSON.stringify(updatedSales, null, 2)};\n`;
            fs.writeFile(jsPath, jsContent, 'utf8', (err3) => {
                if (err3) console.error('Failed to write sales_summary.js:', err3);
                res.json({ success: true, message: 'Transaction deleted' });
            });
        });
    });
});

// GET Sales Endings (About Us page records)
app.get('/api/sales/end', (req, res) => {
    const filePath = path.join(__dirname, 'sales_endings.json');
    fs.readFile(filePath, 'utf8', (err, data) => {
        if (err) return res.status(500).json({ error: 'Failed to read sales endings' });
        try {
            res.json(JSON.parse(data));
        } catch (e) {
            res.json([]);
        }
    });
});

// POST new sales ending
app.post('/api/sales/end', (req, res) => {
    const record = req.body;
    const jsonPath = path.join(__dirname, 'sales_endings.json');
    const jsPath = path.join(__dirname, 'sales_endings.js');

    fs.readFile(jsonPath, 'utf8', (err, data) => {
        let endings = [];
        if (!err) {
            try { endings = JSON.parse(data); } catch (e) { endings = []; }
        }
        endings.push(record);

        fs.writeFile(jsonPath, JSON.stringify(endings, null, 2), 'utf8', (err2) => {
            if (err2) return res.status(500).json({ error: 'Failed to write sales endings' });

            const jsContent = `// This file is auto-generated by the server. Do not edit directly.\nconst salesEndingsData = ${JSON.stringify(endings, null, 2)};\n`;
            fs.writeFile(jsPath, jsContent, 'utf8', (err3) => {
                if (err3) console.error('Failed to write sales_endings.js:', err3);
                res.json({ success: true, message: 'Sales endings saved' });
            });
        });
    });
});

// Clear Sales Endings
app.post('/api/sales/end/clear', (req, res) => {
    const jsonPath = path.join(__dirname, 'sales_endings.json');
    const jsPath = path.join(__dirname, 'sales_endings.js');

    fs.writeFile(jsonPath, '[]', 'utf8', (err) => {
        if (err) return res.status(500).json({ error: 'Failed to clear sales endings' });
        const jsContent = `// This file is auto-generated by the server. Do not edit directly.\nconst salesEndingsData = [];\n`;
        fs.writeFile(jsPath, jsContent, 'utf8', (err2) => {
            if (err2) console.error('Failed to write sales_endings.js:', err2);
            res.json({ success: true, message: 'Sales endings cleared' });
        });
    });
});

// Fallback to index.html for undefined routes
app.get('*all', (req, res) => {
    res.sendFile(path.join(__dirname, 'index.html'));
});

app.listen(PORT, () => {
    console.log('\n==================================================');
    console.log(`Moonlight Icecream Parlour Server is running!`);
    console.log(`Access the application at: http://localhost:${PORT}`);
    console.log(`Admin Password: ${PASSWORD}`);
    console.log('==================================================\n');
});
